"""Add author to Blogpost

Revision ID: a3010130388b
Revises: 37aa6def70d0
Create Date: 2024-08-27 23:09:42.618724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3010130388b'
down_revision = '37aa6def70d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_blogpost_author_id',  # Name of the foreign key constraint
            'user',  # The reference table
            ['author_id'],  # Local column in 'blogpost' table
            ['id']  # Referenced column in 'user' table
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpost', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blogpost_author_id', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
